version: "3.7"

# 컴퓨터들
services:
  # Backend Computer
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/app/index.js
      - ./email.js:/app/email.js
      # - ./src:/app/src 폴더로 한번에 공유하는 방법
    ports:
      - 8080:8080

  # DB Computer
  db:
    image: mongo:5 # 한줄 밖에 없는 경우는 image로 써도 무방
    # build:
    #   context: .
    #   dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
