version: "1.0"

services:
  test-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
    ports:
      - "3002:3002"

  test-mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
