version: "3.7"

# 컴퓨터들
services:
  # Backend Computer
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  # DB Computer
  db:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
