import LayoutGlobalAndLocal from "@/commons/layout/02-03-layout-header-local";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LayoutTransparent from "@/commons/layout/02-04-layout-header-transparent";
import LayoutFooter from "@/commons/layout/02-05-layout-footer";
import DeviceSetting from "@/commons/settings/03-06-device-setting";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 02-02-layout-header-global */}
        {/* <Layout>{children}</Layout> */}

        {/* 02-03-layout-header-local */}
        {/* <LayoutGlobalAndLocal>{children}</LayoutGlobalAndLocal> */}

        {/* 02-04-layout-header-transparent */}
        {/* <LayoutTransparent>{children}</LayoutTransparent> */}

        {/* 02-05-layout-footer */}
        {/* <LayoutFooter>{children}</LayoutFooter> */}

        {/* 03-06-device-setting */}
        <DeviceSetting>{children}</DeviceSetting>
      </body>
    </html>
  );
}
